alias rc='rails console'
alias rg='rails generate'
alias rd='rails destroy'
alias tlog='tail -fn150 log/development.log'
alias migrate='rake db:migrate db:test:clone'
alias rst='touch tmp/restart.txt'
