alias rc='bundle exec rails console'
alias rg='bundle exec rails generate'
alias rd='bundle exec rails destroy'
alias tlog='tail -fn150 log/development.log'
alias migrate='bundle exec rake db:migrate'
alias rst='touch tmp/restart.txt'
